language: en
pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100  
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: ResponseSelector
    epochs: 100
  - name: "SklearnIntentClassifier"
  - name: "DucklingHTTPExtractor"
    url: "http://0.0.0.0:8000"
    dimensions: ["time","number"]
    locale: "en_GB"
    timezone: "Asia/Mumbai"

policies:
- name: MemoizationPolicy
- name: MappingPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 200
- name: RulePolicy